// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleHound.SQLDatabase;

namespace SimpleHound.Migrations
{
    [DbContext(typeof(MenuDBContext))]
    [Migration("20210826163619_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleHound.SQLDatabase.CustomerCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Customer");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("CustomerCount");
                });

            modelBuilder.Entity("SimpleHound.SQLDatabase.MenuCustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Customer");

                    b.Property<string>("EmployeeName");

                    b.Property<string>("FoodItem");

                    b.Property<string>("Note");

                    b.Property<string>("Password");

                    b.Property<decimal>("Price");

                    b.Property<int>("Quantity");

                    b.Property<int>("TableNum");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("MenuCustomerOrder");
                });

            modelBuilder.Entity("SimpleHound.SQLDatabase.MenuEmployees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Position");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("MenuEmployees");
                });

            modelBuilder.Entity("SimpleHound.SQLDatabase.MenuEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categories");

                    b.Property<string>("Items");

                    b.Property<decimal>("Prices");

                    b.Property<int>("Tables");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("MenuEntry");
                });

            modelBuilder.Entity("SimpleHound.SQLDatabase.MenuKitchenOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Customer");

                    b.Property<string>("EmployeeName");

                    b.Property<string>("FoodItem");

                    b.Property<string>("Note");

                    b.Property<string>("Password");

                    b.Property<decimal>("Price");

                    b.Property<int>("Quantity");

                    b.Property<int>("TableNum");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("MenuKitchen");
                });
#pragma warning restore 612, 618
        }
    }
}
